Script started on Mon Sep 30 19:16:01 2019
]0;tyfu@klaatu:~[?1034h[tyfu@klaatu ~]$ whoami
tyfu
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ echo $SHELL
/bin/bash
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ pwd
/homes/tyfu
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ uname -a
Linux klaatu.cs.washington.edu 4.14.145-1.el7.retpoline.x86_64 #1 SMP Thu Sep 19 08:49:41 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ gcc -- [Kversion -std=c11
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

]0;tyfu@klaatu:~[tyfu@klaatu ~]$ python -v[K-version
Python 2.7.5
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ h[Kjava -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ javac -version
javac 1.8.0_222
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ chmod -help
chmod: invalid option -- 'h'
Try 'chmod --help' for more information.
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ chmod --help
Usage: chmod [OPTION]... MODE[,MODE]... FILE...
  or:  chmod [OPTION]... OCTAL-MODE FILE...
  or:  chmod [OPTION]... --reference=RFILE FILE...
Change the mode of each FILE to MODE.
With --reference, change the mode of each FILE to that of RFILE.

  -c, --changes          like verbose but report only when a change is made
  -f, --silent, --quiet  suppress most error messages
  -v, --verbose          output a diagnostic for every file processed
      --no-preserve-root  do not treat '/' specially (the default)
      --preserve-root    fail to operate recursively on '/'
      --reference=RFILE  use RFILE's mode instead of MODE values
  -R, --recursive        change files and directories recursively
      --help     display this help and exit
      --version  output version information and exit

Each MODE is of the form '[ugoa]*([-+=]([rwxXst]*|[ugo]))+|[-+=][0-7]+'.

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Report chmod translation bugs to <http://translationproject.org/team/>
For complete documentation, run: info coreutils 'chmod invocation'
]0;tyfu@klaatu:~[tyfu@klaatu ~]$ exit
exit

Script done on Mon Sep 30 19:17:07 2019
